name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'DongPoTea.Web/**'
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - 'DongPoTea.Web/**'

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'DongPoTea.Web/package-lock.json'

      - name: Install dependencies
        run: |
          cd DongPoTea.Web
          npm ci

      - name: Run tests
        run: |
          cd DongPoTea.Web
          npm run test -- --coverage --passWithNoTests --watchAll=false

      - name: Build application
        run: |
          cd DongPoTea.Web
          npm run build
        env:
          CI: false
          GENERATE_SOURCEMAP: false

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_MUSHROOM_0F8320A10 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/DongPoTea.Web"
          output_location: "build"
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DELIGHTFUL_MUSHROOM_0F8320A10 }}
          action: "close"